# Generated by Django 3.2.4 on 2021-06-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Seminar', 'Seminar'), ('Conference', 'Conference'), ('Presentation', 'Presentation')], default='Presentation', max_length=12)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('adult_price', models.FloatField()),
                ('discount_price', models.FloatField()),
            ],
        ),
    ]
