# Generated by Django 3.2.4 on 2021-06-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('adult_price', models.FloatField()),
                ('child_price', models.FloatField()),
                ('event_description', models.CharField(max_length=200)),
                ('event_image', models.ImageField(default='default.jpg', upload_to='event_image')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegisterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('adult_qty', models.IntegerField()),
                ('child_qty', models.IntegerField()),
            ],
        ),
    ]
