# Generated by Django 3.2.4 on 2021-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Seminar', 'Seminar'), ('Presentation', 'Presentation')], max_length=100),
        ),
    ]
