# Generated by Django 3.2.3 on 2021-06-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='discount_price',
            new_name='child_price',
        ),
    ]
